---
- name: Install NGINX
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Start and enable NGINX
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Deploy custom index page
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
